import { Meeting } from '../types';

export const EXACT_MEETINGS_CJR: Meeting[] = [
  {
    id: 'meet-cjr-2026-06-23',
    committeeId: 'com-cjr',
    committeeName: 'Comissão de Justiça e Redação',
    date: '2026-06-23',
    time: '14:00',
    location: 'Sala das Comissões Parlamentares',
    topic: 'Projetos de Lei nº 23, 24 e 25/2026',
    description: 'Apreciação da constitucionalidade, legalidade e regimentalidade dos Projetos de Lei nº 23, 24 e 25/2026.',
    status: 'realizada',
    attendances: [
      {
        councilorId: 'c-07',
        councilorName: 'João Elton Rangel',
        committeeRole: 'Presidente',
        politicalParty: 'MDB',
        status: 'presente',
        justificationReason: '',
        justificationDocument: '',
        justificationSigned: false,
      },
      {
        councilorId: 'c-08',
        councilorName: 'Ângelo Joacir Buratti',
        committeeRole: 'Relator',
        politicalParty: 'PL',
        status: 'ausente_injustificado',
        justificationReason: '',
        justificationDocument: '',
        justificationSigned: false,
      },
      {
        councilorId: 'c-02',
        councilorName: 'Zélia Fiorese Cupini',
        committeeRole: 'Membro',
        politicalParty: 'PP',
        status: 'presente',
        justificationReason: '',
        justificationDocument: '',
        justificationSigned: false,
      },
    ],
    minutesText: `ATA DA REUNIÃO DA COMISSÃO DE JUSTIÇA E REDAÇÃO (CJR) DA CÂMARA MUNICIPAL.
Aos vinte e três dias do mês de junho do ano de dois mil e vinte e seis, às quatorze horas, reuniu-se a Comissão de Justiça e Redação na Sala das Comissões Parlamentares.
Presentes os vereadores: João Elton Rangel (Presidente) e Zélia Fiorese Cupini (Membro). Registrada a ausência não justificada do Vereador Ângelo Joacir Buratti (Relator).
Havendo quórum regimental da maioria dos membros, abriu-se a sessão para deliberação da pauta: Projetos de Lei nº 23, 24 e 25/2026.
Após análise e debate quanto aos aspectos constitucionais e jurídicos, foi emitido parecer favorável às proposições. Nada mais a tratar, encerrou-se a reunião e lavrou-se a presente ata.`,
    minutesApproved: true,
    createdAt: new Date('2026-06-23T14:00:00').toISOString(),
    updatedAt: new Date('2026-06-23T15:15:00').toISOString(),
  },
  {
    id: 'meet-cjr-2026-07-14',
    committeeId: 'com-cjr',
    committeeName: 'Comissão de Justiça e Redação',
    date: '2026-07-14',
    time: '14:00',
    location: 'Sala das Comissões Parlamentares',
    topic: 'Projeto de Lei nº 26/2026 e 27/2026',
    description: 'Apreciação e emissão de parecer sobre a constitucionalidade e legalidade dos Projetos de Lei nº 26/2026 e 27/2026.',
    status: 'realizada',
    attendances: [
      {
        councilorId: 'c-07',
        councilorName: 'João Elton Rangel',
        committeeRole: 'Presidente',
        politicalParty: 'MDB',
        status: 'ausente_injustificado',
        justificationReason: '',
        justificationDocument: '',
        justificationSigned: false,
      },
      {
        councilorId: 'c-08',
        councilorName: 'Ângelo Joacir Buratti',
        committeeRole: 'Relator',
        politicalParty: 'PL',
        status: 'presente',
        justificationReason: '',
        justificationDocument: '',
        justificationSigned: false,
      },
      {
        councilorId: 'c-02',
        councilorName: 'Zélia Fiorese Cupini',
        committeeRole: 'Membro',
        politicalParty: 'PP',
        status: 'presente',
        justificationReason: '',
        justificationDocument: '',
        justificationSigned: false,
      },
    ],
    minutesText: `ATA DA REUNIÃO DA COMISSÃO DE JUSTIÇA E REDAÇÃO (CJR) DA CÂMARA MUNICIPAL.
Aos quatorze dias do mês de julho do ano de dois mil e vinte e seis, às quatorze horas, reuniu-se a Comissão de Justiça e Redação.
Presentes os vereadores: Ângelo Joacir Buratti (Relator) e Zélia Fiorese Cupini (Membro). Registrada a ausência não justificada do Presidente Vereador João Elton Rangel.
Havendo quórum legal (maioria dos membros), realizou-se a deliberação da pauta: Projetos de Lei nº 26/2026 e 27/2026.
O relator emitiu parecer favorável quanto à legalidade e regimentalidade, com anuência da maioria presente. Lavrou-se a presente ata.`,
    minutesApproved: true,
    createdAt: new Date('2026-07-14T14:00:00').toISOString(),
    updatedAt: new Date('2026-07-14T14:45:00').toISOString(),
  },
  {
    id: 'meet-cjr-2026-07-21',
    committeeId: 'com-cjr',
    committeeName: 'Comissão de Justiça e Redação',
    date: '2026-07-21',
    time: '14:00',
    location: 'Sala das Comissões Parlamentares',
    topic: 'Projeto de Lei nº 28/2026',
    description: 'Exame de constitucionalidade, legalidade e boa técnica legislativa do Projeto de Lei nº 28/2026.',
    status: 'realizada',
    attendances: [
      {
        councilorId: 'c-07',
        councilorName: 'João Elton Rangel',
        committeeRole: 'Presidente',
        politicalParty: 'MDB',
        status: 'presente',
        justificationReason: '',
        justificationDocument: '',
        justificationSigned: false,
      },
      {
        councilorId: 'c-08',
        councilorName: 'Ângelo Joacir Buratti',
        committeeRole: 'Relator',
        politicalParty: 'PL',
        status: 'presente',
        justificationReason: '',
        justificationDocument: '',
        justificationSigned: false,
      },
      {
        councilorId: 'c-02',
        councilorName: 'Zélia Fiorese Cupini',
        committeeRole: 'Membro',
        politicalParty: 'PP',
        status: 'presente',
        justificationReason: '',
        justificationDocument: '',
        justificationSigned: false,
      },
    ],
    minutesText: `ATA DA REUNIÃO DA COMISSÃO DE JUSTIÇA E REDAÇÃO (CJR) DA CÂMARA MUNICIPAL.
Aos vinte e um dias do mês de julho do ano de dois mil e vinte e seis, às quatorze horas, reuniu-se a Comissão de Justiça e Redação na Sala das Comissões Parlamentares com quórum integral.
Presentes todos os vereadores: João Elton Rangel (Presidente), Ângelo Joacir Buratti (Relator) e Zélia Fiorese Cupini (Membro).
Pauta: Projeto de Lei nº 28/2026.
Examinada a matéria pelo relator e constatada plena conformidade jurídica e constitucional, foi exarado parecer favorável unânime. Lavrou-se a presente ata.`,
    minutesApproved: true,
    createdAt: new Date('2026-07-21T14:00:00').toISOString(),
    updatedAt: new Date('2026-07-21T15:20:00').toISOString(),
  },
  {
    id: 'meet-cjr-2026-08-18',
    committeeId: 'com-cjr',
    committeeName: 'Comissão de Justiça e Redação',
    date: '2026-08-18',
    time: '14:00',
    location: 'Sala das Comissões Parlamentares',
    topic: 'Projeto de Resolução nº 03/2026 e nº 04/2026',
    description: 'Apreciação e emissão de parecer sobre a constitucionalidade e regimentalidade dos Projetos de Resolução nº 03/2026 e nº 04/2026.',
    status: 'realizada',
    attendances: [
      {
        councilorId: 'c-07',
        councilorName: 'João Elton Rangel',
        committeeRole: 'Presidente',
        politicalParty: 'MDB',
        status: 'presente',
        justificationReason: '',
        justificationDocument: '',
        justificationSigned: false,
      },
      {
        councilorId: 'c-08',
        councilorName: 'Ângelo Joacir Buratti',
        committeeRole: 'Relator',
        politicalParty: 'PL',
        status: 'presente',
        justificationReason: '',
        justificationDocument: '',
        justificationSigned: false,
      },
      {
        councilorId: 'c-02',
        councilorName: 'Zélia Fiorese Cupini',
        committeeRole: 'Membro',
        politicalParty: 'PP',
        status: 'presente',
        justificationReason: '',
        justificationDocument: '',
        justificationSigned: false,
      },
    ],
    minutesText: `ATA DA REUNIÃO DA COMISSÃO DE JUSTIÇA E REDAÇÃO (CJR) DA CÂMARA MUNICIPAL.
Aos dezoito dias do mês de agosto do ano de dois mil e vinte e seis, às quatorze horas, reuniu-se a Comissão de Justiça e Redação com quórum total de 100%.
Presentes os vereadores: João Elton Rangel (Presidente), Ângelo Joacir Buratti (Relator) e Zélia Fiorese Cupini (Membro).
Pauta: Projetos de Resolução nº 03/2026 e nº 04/2026.
A comissão deliberou unanimemente pela aprovação dos pareceres favoráveis às proposições regimentais. Nada mais havendo, lavrou-se a ata.`,
    minutesApproved: true,
    createdAt: new Date('2026-08-18T14:00:00').toISOString(),
    updatedAt: new Date('2026-08-18T15:10:00').toISOString(),
  },
  {
    id: 'meet-cjr-2026-08-25',
    committeeId: 'com-cjr',
    committeeName: 'Comissão de Justiça e Redação',
    date: '2026-08-25',
    time: '14:00',
    location: 'Sala das Comissões Parlamentares',
    topic: 'Projeto de Lei nº 29/2026 e nº 30/2026',
    description: 'Análise de constitucionalidade, legalidade e técnica legislativa dos Projetos de Lei nº 29/2026 e nº 30/2026.',
    status: 'realizada',
    attendances: [
      {
        councilorId: 'c-07',
        councilorName: 'João Elton Rangel',
        committeeRole: 'Presidente',
        politicalParty: 'MDB',
        status: 'presente',
        justificationReason: '',
        justificationDocument: '',
        justificationSigned: false,
      },
      {
        councilorId: 'c-08',
        councilorName: 'Ângelo Joacir Buratti',
        committeeRole: 'Relator',
        politicalParty: 'PL',
        status: 'presente',
        justificationReason: '',
        justificationDocument: '',
        justificationSigned: false,
      },
      {
        councilorId: 'c-02',
        councilorName: 'Zélia Fiorese Cupini',
        committeeRole: 'Membro',
        politicalParty: 'PP',
        status: 'presente',
        justificationReason: '',
        justificationDocument: '',
        justificationSigned: false,
      },
    ],
    minutesText: `ATA DA REUNIÃO DA COMISSÃO DE JUSTIÇA E REDAÇÃO (CJR) DA CÂMARA MUNICIPAL.
Aos vinte e cinco dias do mês de agosto do ano de dois mil e vinte e seis, às quatorze horas, reuniu-se a Comissão de Justiça e Redação.
Presentes: João Elton Rangel (Presidente), Ângelo Joacir Buratti (Relator) e Zélia Fiorese Cupini (Membro).
Pauta: Projetos de Lei nº 29/2026 e nº 30/2026.
Após detalhado relatório e deliberação, as matérias foram aprovadas sem restrições jurídicas. Encerrou-se a reunião e lavrou-se a ata.`,
    minutesApproved: true,
    createdAt: new Date('2026-08-25T14:00:00').toISOString(),
    updatedAt: new Date('2026-08-25T15:20:00').toISOString(),
  },
  {
    id: 'meet-cjr-2026-09-01',
    committeeId: 'com-cjr',
    committeeName: 'Comissão de Justiça e Redação',
    date: '2026-09-01',
    time: '14:00',
    location: 'Sala das Comissões Parlamentares',
    topic: 'Projeto de Lei nº 31/2026',
    description: 'Apreciação e deliberação de parecer sobre o Projeto de Lei nº 31/2026.',
    status: 'realizada',
    attendances: [
      {
        councilorId: 'c-07',
        councilorName: 'João Elton Rangel',
        committeeRole: 'Presidente',
        politicalParty: 'MDB',
        status: 'presente',
        justificationReason: '',
        justificationDocument: '',
        justificationSigned: false,
      },
      {
        councilorId: 'c-08',
        councilorName: 'Ângelo Joacir Buratti',
        committeeRole: 'Relator',
        politicalParty: 'PL',
        status: 'presente',
        justificationReason: '',
        justificationDocument: '',
        justificationSigned: false,
      },
      {
        councilorId: 'c-02',
        councilorName: 'Zélia Fiorese Cupini',
        committeeRole: 'Membro',
        politicalParty: 'PP',
        status: 'ausente_injustificado',
        justificationReason: '',
        justificationDocument: '',
        justificationSigned: false,
      },
    ],
    minutesText: `ATA DA REUNIÃO DA COMISSÃO DE JUSTIÇA E REDAÇÃO (CJR) DA CÂMARA MUNICIPAL.
Ao primeiro dia do mês de setembro do ano de dois mil e vinte e seis, às quatorze horas, reuniu-se a Comissão de Justiça e Redação na Sala das Comissões Parlamentares.
Presentes os vereadores: João Elton Rangel (Presidente) e Ângelo Joacir Buratti (Relator). Registrada a ausência não justificada da Vereadora Zélia Fiorese Cupini.
Havendo quórum legal (maioria absoluta), abriu-se a deliberação da matéria pautada: Projeto de Lei nº 31/2026.
O relator votou pela legalidade e constitucionalidade do projeto, obtendo concordância do Presidente. Emitido parecer favorável e lavrada a presente ata.`,
    minutesApproved: true,
    createdAt: new Date('2026-09-01T14:00:00').toISOString(),
    updatedAt: new Date('2026-09-01T15:15:00').toISOString(),
  },
  {
    id: 'meet-cjr-2026-09-15',
    committeeId: 'com-cjr',
    committeeName: 'Comissão de Justiça e Redação',
    date: '2026-09-15',
    time: '14:00',
    location: 'Sala das Comissões Parlamentares',
    topic: 'Projeto de Lei nº 32/2026 e 34/2026',
    description: 'Parecer de constitucionalidade, juridicidade e redação sobre os Projetos de Lei nº 32/2026 e 34/2026.',
    status: 'realizada',
    attendances: [
      {
        councilorId: 'c-07',
        councilorName: 'João Elton Rangel',
        committeeRole: 'Presidente',
        politicalParty: 'MDB',
        status: 'presente',
        justificationReason: '',
        justificationDocument: '',
        justificationSigned: false,
      },
      {
        councilorId: 'c-08',
        councilorName: 'Ângelo Joacir Buratti',
        committeeRole: 'Relator',
        politicalParty: 'PL',
        status: 'presente',
        justificationReason: '',
        justificationDocument: '',
        justificationSigned: false,
      },
      {
        councilorId: 'c-02',
        councilorName: 'Zélia Fiorese Cupini',
        committeeRole: 'Membro',
        politicalParty: 'PP',
        status: 'presente',
        justificationReason: '',
        justificationDocument: '',
        justificationSigned: false,
      },
    ],
    minutesText: `ATA DA REUNIÃO DA COMISSÃO DE JUSTIÇA E REDAÇÃO (CJR) DA CÂMARA MUNICIPAL.
Aos quinze dias do mês de setembro do ano de dois mil e vinte e seis, às quatorze horas, reuniu-se a Comissão de Justiça e Redação.
Composição integral presente: João Elton Rangel (Presidente), Ângelo Joacir Buratti (Relator) e Zélia Fiorese Cupini (Membro). Quórum de 100%.
Pauta: Projetos de Lei nº 32/2026 e nº 34/2026.
Ambas as matérias foram debatidas e consideradas constitucionais e regimentais, sendo emitidos pareceres favoráveis por unanimidade. Lavrou-se a ata.`,
    minutesApproved: true,
    createdAt: new Date('2026-09-15T14:00:00').toISOString(),
    updatedAt: new Date('2026-09-15T15:20:00').toISOString(),
  },
  {
    id: 'meet-cjr-2026-09-25',
    committeeId: 'com-cjr',
    committeeName: 'Comissão de Justiça e Redação',
    date: '2026-09-25',
    time: '14:00',
    location: 'Sala das Comissões Parlamentares',
    topic: 'Projeto de Lei nº 35/2026',
    description: 'Exame de constitucionalidade, legalidade e adequação regimental do Projeto de Lei nº 35/2026.',
    status: 'realizada',
    attendances: [
      {
        councilorId: 'c-07',
        councilorName: 'João Elton Rangel',
        committeeRole: 'Presidente',
        politicalParty: 'MDB',
        status: 'presente',
        justificationReason: '',
        justificationDocument: '',
        justificationSigned: false,
      },
      {
        councilorId: 'c-08',
        councilorName: 'Ângelo Joacir Buratti',
        committeeRole: 'Relator',
        politicalParty: 'PL',
        status: 'ausente_injustificado',
        justificationReason: '',
        justificationDocument: '',
        justificationSigned: false,
      },
      {
        councilorId: 'c-02',
        councilorName: 'Zélia Fiorese Cupini',
        committeeRole: 'Membro',
        politicalParty: 'PP',
        status: 'presente',
        justificationReason: '',
        justificationDocument: '',
        justificationSigned: false,
      },
    ],
    minutesText: `ATA DA REUNIÃO DA COMISSÃO DE JUSTIÇA E REDAÇÃO (CJR) DA CÂMARA MUNICIPAL.
Aos vinte e cinco dias do mês de setembro do ano de dois mil e vinte e seis, às quatorze horas, reuniu-se a Comissão de Justiça e Redação na Sala das Comissões Parlamentares.
Presentes os vereadores: João Elton Rangel (Presidente) e Zélia Fiorese Cupini (Membro). Registrada a ausência sem justificativa do Vereador Ângelo Joacir Buratti (Relator).
Havendo quórum regimental da maioria dos membros, passou-se à apreciação da pauta: Projeto de Lei nº 35/2026.
Designada a vereadora Zélia Fiorese Cupini para relatar a matéria ad hoc, foi proferido parecer favorável à constitucionalidade da proposição, aprovado pelos presentes. Encerrou-se a reunião e lavrou-se a ata.`,
    minutesApproved: true,
    createdAt: new Date('2026-09-25T14:00:00').toISOString(),
    updatedAt: new Date('2026-09-25T15:15:00').toISOString(),
  },
];
